version: 1
defaults:
  - bert_config: bert
  - _self_ # values defined in _this_ take precedence over defaults

train_file: [
  "/net/acadia10a/data/zkhan/coco2017/pretrain-pairs.json",
               ]

image_res: 256
vision_width: 768
embed_dim: 256
batch_size: 128
temp: 0.07
mlm_probability: 0.15
queue_size: 65536
momentum: 0.995
alpha: 0.4
image_tokenizer_path: /net/acadia10a/data/zkhan/dall-e-tokenizer-weights

optimizer: {opt: adamW, lr: 1e-4, weight_decay: 0.02}
schedular: {sched: cosine, lr: 1e-4, epochs: 15, min_lr: 1e-5, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 10, cooldown_epochs: 0}

disable_wandb: true

vit_mask_token: false

model_config:
  import_path: models.clip.CLIP